#set the window appearance
#TERM = xterm-256color

[window]
opacity = 0.9
title = "Alicritty"

#font design/styles
[font]
normal = { family = "Consolas", style = "Regular" }
size = 10


#import from pywal16
#[general]
#import = [
#    "~/.cache/wal/colors-alacritty.toml",
#]

